<!DOCTYPE html>
<html xmlns="http://www.w3.org/1999/xhtml" lang="en" xml:lang="en"><head>

<meta charset="utf-8">
<meta name="generator" content="quarto-1.6.42">

<meta name="viewport" content="width=device-width, initial-scale=1.0, user-scalable=yes">

<meta name="author" content="Arisara Therdthianwong">
<meta name="author" content="Quanyu Qian">
<meta name="author" content="Dhruv Kaushal Gal">

<title>Global Renewable Energy Leaders in 2023</title>
<style>
code{white-space: pre-wrap;}
span.smallcaps{font-variant: small-caps;}
div.columns{display: flex; gap: min(4vw, 1.5em);}
div.column{flex: auto; overflow-x: auto;}
div.hanging-indent{margin-left: 1.5em; text-indent: -1.5em;}
ul.task-list{list-style: none;}
ul.task-list li input[type="checkbox"] {
  width: 0.8em;
  margin: 0 0.8em 0.2em -1em; /* quarto-specific, see https://github.com/quarto-dev/quarto-cli/issues/4556 */ 
  vertical-align: middle;
}
</style>


<script src="Assignment3_files/libs/clipboard/clipboard.min.js"></script>
<script src="Assignment3_files/libs/quarto-html/quarto.js"></script>
<script src="Assignment3_files/libs/quarto-html/popper.min.js"></script>
<script src="Assignment3_files/libs/quarto-html/tippy.umd.min.js"></script>
<script src="Assignment3_files/libs/quarto-html/anchor.min.js"></script>
<link href="Assignment3_files/libs/quarto-html/tippy.css" rel="stylesheet">
<link href="Assignment3_files/libs/quarto-html/quarto-syntax-highlighting-2f5df379a58b258e96c21c0638c20c03.css" rel="stylesheet" id="quarto-text-highlighting-styles">
<script src="Assignment3_files/libs/bootstrap/bootstrap.min.js"></script>
<link href="Assignment3_files/libs/bootstrap/bootstrap-icons.css" rel="stylesheet">
<link href="Assignment3_files/libs/bootstrap/bootstrap-c0367b04c37547644fece4185067e4a7.min.css" rel="stylesheet" append-hash="true" id="quarto-bootstrap" data-mode="light">


</head>

<body>

<div id="quarto-content" class="page-columns page-rows-contents page-layout-article">
<div id="quarto-margin-sidebar" class="sidebar margin-sidebar">
  <nav id="TOC" role="doc-toc" class="toc-active">
    <h2 id="toc-title">Table of contents</h2>
   
  <ul class="collapse">
  <li><a href="#executive-summary" id="toc-executive-summary" class="nav-link active" data-scroll-target="#executive-summary">Executive summary</a></li>
  <li><a href="#introduction" id="toc-introduction" class="nav-link" data-scroll-target="#introduction">Introduction</a></li>
  <li><a href="#methodology" id="toc-methodology" class="nav-link" data-scroll-target="#methodology">Methodology</a>
  <ul class="collapse">
  <li><a href="#top-10-countries-by-renewable-energy-share-in-2023" id="toc-top-10-countries-by-renewable-energy-share-in-2023" class="nav-link" data-scroll-target="#top-10-countries-by-renewable-energy-share-in-2023">Top 10 Countries by Renewable Energy Share in 2023</a></li>
  <li><a href="#which-country-leads-in-renewable-energy-share-in-2023" id="toc-which-country-leads-in-renewable-energy-share-in-2023" class="nav-link" data-scroll-target="#which-country-leads-in-renewable-energy-share-in-2023">Which country leads in renewable energy share in 2023?</a></li>
  <li><a href="#why-norway-ranks-highest-globally-in-renewable-energy-share" id="toc-why-norway-ranks-highest-globally-in-renewable-energy-share" class="nav-link" data-scroll-target="#why-norway-ranks-highest-globally-in-renewable-energy-share">Why Norway ranks highest globally in renewable energy share?</a></li>
  <li><a href="#results" id="toc-results" class="nav-link" data-scroll-target="#results">Results</a></li>
  <li><a href="#discussion-and-conclusion" id="toc-discussion-and-conclusion" class="nav-link" data-scroll-target="#discussion-and-conclusion">Discussion and Conclusion</a></li>
  <li><a href="#references" id="toc-references" class="nav-link" data-scroll-target="#references">References</a></li>
  </ul></li>
  </ul>
<div class="quarto-alternate-formats"><h2>Other Formats</h2><ul><li><a href="Assignment3.pdf"><i class="bi bi-file-pdf"></i>PDF</a></li></ul></div></nav>
</div>
<main class="content" id="quarto-document-content">

<header id="title-block-header" class="quarto-title-block default">
<div class="quarto-title">
<h1 class="title">Global Renewable Energy Leaders in 2023</h1>
</div>



<div class="quarto-title-meta">

    <div>
    <div class="quarto-title-meta-heading">Authors</div>
    <div class="quarto-title-meta-contents">
             <p>Arisara Therdthianwong </p>
             <p>Quanyu Qian </p>
             <p>Dhruv Kaushal Gal </p>
          </div>
  </div>
    
  
    
  </div>
  


</header>


<section id="executive-summary" class="level2">
<h2 class="anchored" data-anchor-id="executive-summary">Executive summary</h2>
<p>This report investigates the top 10 countries with the highest renewable energy share in 2023 and global trends in energy transitions. It further analyzes the sources of renewable energy in the leading country. The analysis is conducted using reliable data from Our World in Data. Among these countries, Norway stands out as a global leader with 72.09% of its primary energy coming from renewable sources. The findings offer valuable insight to effectively implement national approaches that could transform sustainable energy transitions worldwide.</p>
<div style="page-break-after: always;"></div>
</section>
<section id="introduction" class="level2">
<h2 class="anchored" data-anchor-id="introduction">Introduction</h2>
<p>The global energy landscape has transformed rapidly in the last few decades. Many countries are undergoing a major shift toward adopting renewable sources such as hydropower, wind, and solar in response to the challenges of climate change and resource sustainability. Renewable energy now plays an important role as an alternative source that helps to reduce reliance on fossil fuels and mitigate greenhouse gas emissions.</p>
<p>Throughout the report, global renewable energy trends are identified, with a focus on the top 10 countries with highest proportion of renewable energy in total energy consumption in 2023. Norway leads the way, with roughly 72% of primary energy sourced from renewable. Sweden and Brazil are also undergoing significant transitions, with 53.9% and 50.3% renewable shares, respectively.</p>
<p>A deeper analysis on Norway has been conducted to better understand how a developed country manages its energy infrastructure achieving a high level of renewable integration. Understanding these factors behind Norway’s performance can be beneficial for planning and improving renewable energy policies and strategies that could be adapted to different regional and national contexts. This analysis aims to provide a useful insight that can guide future energy transitions globally.</p>
<div style="page-break-after: always;"></div>
</section>
<section id="methodology" class="level1">
<h1>Methodology</h1>
<p>To identify the global leaders in renewable energy share, we used the publicly available dataset from Our World in Data, which includes annual records of renewable energy share by country from 1965 to 2023.</p>
<p>We filtered the dataset to focus exclusively on 2023 and excluded aggregated regions (e.g., World, Europe, Asia), allowing us to rank individual countries by their share of primary energy from renewables.</p>
<p><a href="#tbl-table-top10" class="quarto-xref">Table&nbsp;1</a> lists the top 10 countries with the highest renewable energy share in 2023, and <a href="#fig-top10-bar" class="quarto-xref">Figure&nbsp;1</a> presents a bar chart for direct visual comparison.</p>
<p>To understand why Norway ranks highest globally, we analyzed its national renewable energy composition using a second dataset on electricity generation by source. We examined hydropower, wind, solar, and bioenergy to assess their respective contributions. This breakdown (<a href="#tbl-table-norway-2023" class="quarto-xref">Table&nbsp;2</a> and <a href="#fig-norway-sources" class="quarto-xref">Figure&nbsp;2</a>) shows Norway’s strong dependence on hydropower, which contributes over 90% of its renewable electricity output.</p>
<p>To complement Norway’s national breakdown, we further compared its hydropower generation to other global producers. Although Norway relies heavily on hydropower as a share of its energy mix, <a href="#fig-global-hydro" class="quarto-xref">Figure&nbsp;3</a> reveals that its total generation is also globally significant—enabling a clearer comparison between scale and proportion in renewable leadership.</p>
<section id="top-10-countries-by-renewable-energy-share-in-2023" class="level2">
<h2 class="anchored" data-anchor-id="top-10-countries-by-renewable-energy-share-in-2023">Top 10 Countries by Renewable Energy Share in 2023</h2>
<p>We filtered the dataset to include only the year 2023. The processed data identifies the top 10 countries with the highest share of renewable energy.</p>
<p><a href="#tbl-table-top10" class="quarto-xref">Table&nbsp;1</a> lists these countries; <a href="#fig-top10-bar" class="quarto-xref">Figure&nbsp;1</a> visualizes the comparison.</p>
<div class="cell">
<div id="tbl-table-top10" class="cell quarto-float quarto-figure quarto-figure-center anchored">
<figure class="quarto-float quarto-float-tbl figure">
<figcaption class="quarto-float-caption-top quarto-float-caption quarto-float-tbl" id="tbl-table-top10-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
Table&nbsp;1: Top 10 Countries by Share of Renewable Energy in 2023
</figcaption>
<div aria-describedby="tbl-table-top10-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
<div class="cell-output-display">
<table class="do-not-create-environment cell caption-top table table-sm table-striped small">
<thead>
<tr class="header">
<th style="text-align: left;">Country</th>
<th style="text-align: left;">Code</th>
<th style="text-align: right;">Year</th>
<th style="text-align: right;">Renewables (%)</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td style="text-align: left;">Norway</td>
<td style="text-align: left;">NOR</td>
<td style="text-align: right;">2023</td>
<td style="text-align: right;">72.09110</td>
</tr>
<tr class="even">
<td style="text-align: left;">Sweden</td>
<td style="text-align: left;">SWE</td>
<td style="text-align: right;">2023</td>
<td style="text-align: right;">53.89018</td>
</tr>
<tr class="odd">
<td style="text-align: left;">Brazil</td>
<td style="text-align: left;">BRA</td>
<td style="text-align: right;">2023</td>
<td style="text-align: right;">50.33141</td>
</tr>
<tr class="even">
<td style="text-align: left;">Denmark</td>
<td style="text-align: left;">DNK</td>
<td style="text-align: right;">2023</td>
<td style="text-align: right;">42.73486</td>
</tr>
<tr class="odd">
<td style="text-align: left;">New Zealand</td>
<td style="text-align: left;">NZL</td>
<td style="text-align: right;">2023</td>
<td style="text-align: right;">42.26695</td>
</tr>
<tr class="even">
<td style="text-align: left;">Austria</td>
<td style="text-align: left;">AUT</td>
<td style="text-align: right;">2023</td>
<td style="text-align: right;">40.08019</td>
</tr>
<tr class="odd">
<td style="text-align: left;">Switzerland</td>
<td style="text-align: left;">CHE</td>
<td style="text-align: right;">2023</td>
<td style="text-align: right;">38.32534</td>
</tr>
<tr class="even">
<td style="text-align: left;">Portugal</td>
<td style="text-align: left;">PRT</td>
<td style="text-align: right;">2023</td>
<td style="text-align: right;">36.04341</td>
</tr>
<tr class="odd">
<td style="text-align: left;">Finland</td>
<td style="text-align: left;">FIN</td>
<td style="text-align: right;">2023</td>
<td style="text-align: right;">35.93626</td>
</tr>
<tr class="even">
<td style="text-align: left;">South and Central America (EI)</td>
<td style="text-align: left;">NA</td>
<td style="text-align: right;">2023</td>
<td style="text-align: right;">35.39018</td>
</tr>
</tbody>
</table>
</div>
</div>
</figure>
</div>
</div>
<div class="cell">
<div class="cell-output-display">
<div id="fig-top10-bar" class="quarto-float quarto-figure quarto-figure-center anchored">
<figure class="quarto-float quarto-float-fig figure">
<div aria-describedby="fig-top10-bar-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
<img src="Assignment3_files/figure-html/fig-top10-bar-1.png" class="img-fluid figure-img" width="768">
</div>
<figcaption class="quarto-float-caption-bottom quarto-float-caption quarto-float-fig" id="fig-top10-bar-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
Figure&nbsp;1: Top 10 Countries by Renewable Share in 2023
</figcaption>
</figure>
</div>
</div>
</div>
</section>
<section id="which-country-leads-in-renewable-energy-share-in-2023" class="level2">
<h2 class="anchored" data-anchor-id="which-country-leads-in-renewable-energy-share-in-2023">Which country leads in renewable energy share in 2023?</h2>
<p>Norway ranked first in 2023 by renewable energy share.</p>
<p>To explore why Norway ranked first, we filtered its national records to analyze its renewable energy sources.</p>
<div class="cell">
<div id="tbl-table-norway-2023" class="cell quarto-float quarto-figure quarto-figure-center anchored">
<figure class="quarto-float quarto-float-tbl figure">
<figcaption class="quarto-float-caption-top quarto-float-caption quarto-float-tbl" id="tbl-table-norway-2023-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
Table&nbsp;2: Norway’s Renewable Electricity Generation by Source in 2023 (TWh)
</figcaption>
<div aria-describedby="tbl-table-norway-2023-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
<div class="cell-output-display">
<table class="do-not-create-environment cell caption-top table table-sm table-striped small">
<thead>
<tr class="header">
<th style="text-align: left;">Source</th>
<th style="text-align: right;">TWh</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td style="text-align: left;">wind</td>
<td style="text-align: right;">14.96</td>
</tr>
<tr class="even">
<td style="text-align: left;">hydro</td>
<td style="text-align: right;">135.96</td>
</tr>
<tr class="odd">
<td style="text-align: left;">solar</td>
<td style="text-align: right;">0.17</td>
</tr>
<tr class="even">
<td style="text-align: left;">Other renewables including bioenergy</td>
<td style="text-align: right;">0.26</td>
</tr>
</tbody>
</table>
</div>
</div>
</figure>
</div>
</div>
<div class="cell">
<div class="cell-output-display">
<div id="fig-norway-sources" class="quarto-float quarto-figure quarto-figure-center anchored">
<figure class="quarto-float quarto-float-fig figure">
<div aria-describedby="fig-norway-sources-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
<img src="Assignment3_files/figure-html/fig-norway-sources-1.png" class="img-fluid figure-img" width="576">
</div>
<figcaption class="quarto-float-caption-bottom quarto-float-caption quarto-float-fig" id="fig-norway-sources-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
Figure&nbsp;2: Breakdown of Norway’s Renewable Energy Generation in 2023
</figcaption>
</figure>
</div>
</div>
</div>
<p>As shown in <a href="#fig-norway-sources" class="quarto-xref">Figure&nbsp;2</a>, Norway’s renewable electricity in 2023 is dominated by hydropower, which accounts for approximately 136 TWh, making up more than 90% of its total renewable output. In comparison, wind energy contributed around 15 TWh, which is only about 10% of the total. Both solar energy and other renewables including bioenergy made negligible contributions, with values of 0.17 TWh and 0.26 TWh, respectively.</p>
<p>The limited output from wind and solar indicates that while Norway has made some effort to diversify, its renewable success is not based on technological breadth, but rather on natural geographic advantages.</p>
<p>This clear energy profile lays the foundation for further analysis in the Results section, where we explore the historical, policy, and environmental factors that have enabled Norway’s exceptional performance in renewable integration.</p>
</section>
<section id="why-norway-ranks-highest-globally-in-renewable-energy-share" class="level2">
<h2 class="anchored" data-anchor-id="why-norway-ranks-highest-globally-in-renewable-energy-share">Why Norway ranks highest globally in renewable energy share?</h2>
<p>To further explain why Norway ranks highest globally in renewable energy share, we compare its energy source composition with that of other top-performing countries.</p>
<div class="cell">
<div class="cell-output-display">
<div id="fig-global-hydro" class="quarto-float quarto-figure quarto-figure-center anchored">
<figure class="quarto-float quarto-float-fig figure">
<div aria-describedby="fig-global-hydro-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
<img src="Assignment3_files/figure-html/fig-global-hydro-1.png" class="img-fluid figure-img" width="768">
</div>
<figcaption class="quarto-float-caption-bottom quarto-float-caption quarto-float-fig" id="fig-global-hydro-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
Figure&nbsp;3: Global Hydropower Generation (TWh) in 2023 by Country
</figcaption>
</figure>
</div>
</div>
</div>
<p><a href="#fig-global-hydro" class="quarto-xref">Figure&nbsp;3</a> compares total hydropower generation in 2023 across selected countries. While China leads with over 1,200 TWh, Norway still ranks among the global top producers with approximately 270 TWh — despite its relatively small population and geographic size. This reinforces the idea that Norway’s dominance in renewable energy share is not just a percentage artifact, but supported by substantial hydropower infrastructure and generation capacity. Norway’s natural topography has enabled it to produce a significant amount of clean energy with low variability.</p>
</section>
<section id="results" class="level2">
<h2 class="anchored" data-anchor-id="results">Results</h2>
<p>The analysis revealed that in 2023, Norway led globally in renewable energy adoption, with 72.09% of its primary energy coming from renewable sources, as shown in <a href="#tbl-table-top10" class="quarto-xref">Table&nbsp;1</a>. Sweden (53.9%) and Brazil (50.3%) followed closely, highlighting strong national commitments to clean energy transitions.</p>
<p><a href="#fig-top10-bar" class="quarto-xref">Figure&nbsp;1</a> visualizes these rankings, with Norway’s share standing distinctly above the rest of the top 10. This outperformance reflects long-term national investments and natural hydroelectric potential.</p>
<p>To understand this further, <a href="#tbl-table-norway-2023" class="quarto-xref">Table&nbsp;2</a> and <a href="#fig-norway-sources" class="quarto-xref">Figure&nbsp;2</a> show that Norway’s 2023 electricity mix was over 90% hydropower, supported by modest wind output and minimal solar and bioenergy contributions.</p>
<p>Crucially, <a href="#fig-norway-trend" class="quarto-xref">Figure&nbsp;4</a> illustrates that Norway’s leadership is not new—it has maintained a renewable share above 60% for over two decades. This trend reinforces the country’s sustained commitment to renewable development through stable policy, investment, and infrastructure planning.</p>
<p>Overall, these results demonstrate that top-performing countries combine favorable geography with long-term national strategies. Norway exemplifies how consistent planning and natural resource optimization can produce a globally leading clean energy profile.</p>
<div class="cell">
<div class="cell-output-display">
<div id="fig-norway-trend" class="quarto-float quarto-figure quarto-figure-center anchored">
<figure class="quarto-float quarto-float-fig figure">
<div aria-describedby="fig-norway-trend-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
<img src="Assignment3_files/figure-html/fig-norway-trend-1.png" class="img-fluid figure-img" width="576">
</div>
<figcaption class="quarto-float-caption-bottom quarto-float-caption quarto-float-fig" id="fig-norway-trend-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
Figure&nbsp;4: Norway’s Renewable Energy Share (2000–2023)
</figcaption>
</figure>
</div>
</div>
</div>
</section>
<section id="discussion-and-conclusion" class="level2">
<h2 class="anchored" data-anchor-id="discussion-and-conclusion">Discussion and Conclusion</h2>
<p>Norway’s top ranking in renewable energy share is not incidental—it reflects decades of strategic investment in hydroelectric infrastructure, supported by favorable geography and a stable policy environment. The country’s energy profile, dominated by hydropower, illustrates how natural endowments can be effectively leveraged to transition away from fossil fuels.</p>
<p>However, this reliance on a single dominant source introduces potential vulnerabilities. Climate variability, such as droughts or shifting precipitation patterns, could significantly impact hydroelectric generation. Furthermore, despite its leadership, Norway’s use of wind, solar, and bioenergy remains minimal, indicating untapped potential for diversification.</p>
<p>The global comparison in hydropower generation reinforces Norway’s substantial absolute output relative to its size. This combination of high renewable share and high volume is rare among countries and highlights the effectiveness of long-term, resource-aligned energy planning.</p>
<p>In conclusion, Norway’s case exemplifies how geographic advantages, when matched with consistent national policy and infrastructure investment, can result in world-leading performance in renewable energy integration.</p>
<section id="recommendations" class="level3">
<h3 class="anchored" data-anchor-id="recommendations">Recommendations</h3>
<ul>
<li><strong>Diversify energy sources</strong>: Invest in wind and solar to reduce overreliance on hydropower.</li>
<li><strong>Modernize energy infrastructure</strong>: Improve grid flexibility to integrate more variable renewables.</li>
<li><strong>Export expertise</strong>: Share Norway’s policy, regulatory, and engineering frameworks with other nations.</li>
<li><strong>Support adaptive policy</strong>: Prepare for climate risks by developing redundancy and storage solutions.</li>
</ul>
</section>
</section>
<section id="references" class="level2">
<h2 class="anchored" data-anchor-id="references">References</h2>
<p>Our World in Data. (2024). <em>Renewable energy data explorer</em>. Retrieved from <a href="https://ourworldindata.org/renewable-energy">https://ourworldindata.org/renewable-energy</a></p>
<p>Our World in Data. (2024). <em>Hydropower generation by country</em>. Retrieved from <a href="https://ourworldindata.org/grapher/hydropower-consumption">https://ourworldindata.org/grapher/hydropower-consumption</a></p>
</section>
</section>

</main>
<!-- /main column -->
<script id="quarto-html-after-body" type="application/javascript">
window.document.addEventListener("DOMContentLoaded", function (event) {
  const toggleBodyColorMode = (bsSheetEl) => {
    const mode = bsSheetEl.getAttribute("data-mode");
    const bodyEl = window.document.querySelector("body");
    if (mode === "dark") {
      bodyEl.classList.add("quarto-dark");
      bodyEl.classList.remove("quarto-light");
    } else {
      bodyEl.classList.add("quarto-light");
      bodyEl.classList.remove("quarto-dark");
    }
  }
  const toggleBodyColorPrimary = () => {
    const bsSheetEl = window.document.querySelector("link#quarto-bootstrap");
    if (bsSheetEl) {
      toggleBodyColorMode(bsSheetEl);
    }
  }
  toggleBodyColorPrimary();  
  const icon = "";
  const anchorJS = new window.AnchorJS();
  anchorJS.options = {
    placement: 'right',
    icon: icon
  };
  anchorJS.add('.anchored');
  const isCodeAnnotation = (el) => {
    for (const clz of el.classList) {
      if (clz.startsWith('code-annotation-')) {                     
        return true;
      }
    }
    return false;
  }
  const onCopySuccess = function(e) {
    // button target
    const button = e.trigger;
    // don't keep focus
    button.blur();
    // flash "checked"
    button.classList.add('code-copy-button-checked');
    var currentTitle = button.getAttribute("title");
    button.setAttribute("title", "Copied!");
    let tooltip;
    if (window.bootstrap) {
      button.setAttribute("data-bs-toggle", "tooltip");
      button.setAttribute("data-bs-placement", "left");
      button.setAttribute("data-bs-title", "Copied!");
      tooltip = new bootstrap.Tooltip(button, 
        { trigger: "manual", 
          customClass: "code-copy-button-tooltip",
          offset: [0, -8]});
      tooltip.show();    
    }
    setTimeout(function() {
      if (tooltip) {
        tooltip.hide();
        button.removeAttribute("data-bs-title");
        button.removeAttribute("data-bs-toggle");
        button.removeAttribute("data-bs-placement");
      }
      button.setAttribute("title", currentTitle);
      button.classList.remove('code-copy-button-checked');
    }, 1000);
    // clear code selection
    e.clearSelection();
  }
  const getTextToCopy = function(trigger) {
      const codeEl = trigger.previousElementSibling.cloneNode(true);
      for (const childEl of codeEl.children) {
        if (isCodeAnnotation(childEl)) {
          childEl.remove();
        }
      }
      return codeEl.innerText;
  }
  const clipboard = new window.ClipboardJS('.code-copy-button:not([data-in-quarto-modal])', {
    text: getTextToCopy
  });
  clipboard.on('success', onCopySuccess);
  if (window.document.getElementById('quarto-embedded-source-code-modal')) {
    const clipboardModal = new window.ClipboardJS('.code-copy-button[data-in-quarto-modal]', {
      text: getTextToCopy,
      container: window.document.getElementById('quarto-embedded-source-code-modal')
    });
    clipboardModal.on('success', onCopySuccess);
  }
    var localhostRegex = new RegExp(/^(?:http|https):\/\/localhost\:?[0-9]*\//);
    var mailtoRegex = new RegExp(/^mailto:/);
      var filterRegex = new RegExp('/' + window.location.host + '/');
    var isInternal = (href) => {
        return filterRegex.test(href) || localhostRegex.test(href) || mailtoRegex.test(href);
    }
    // Inspect non-navigation links and adorn them if external
 	var links = window.document.querySelectorAll('a[href]:not(.nav-link):not(.navbar-brand):not(.toc-action):not(.sidebar-link):not(.sidebar-item-toggle):not(.pagination-link):not(.no-external):not([aria-hidden]):not(.dropdown-item):not(.quarto-navigation-tool):not(.about-link)');
    for (var i=0; i<links.length; i++) {
      const link = links[i];
      if (!isInternal(link.href)) {
        // undo the damage that might have been done by quarto-nav.js in the case of
        // links that we want to consider external
        if (link.dataset.originalHref !== undefined) {
          link.href = link.dataset.originalHref;
        }
      }
    }
  function tippyHover(el, contentFn, onTriggerFn, onUntriggerFn) {
    const config = {
      allowHTML: true,
      maxWidth: 500,
      delay: 100,
      arrow: false,
      appendTo: function(el) {
          return el.parentElement;
      },
      interactive: true,
      interactiveBorder: 10,
      theme: 'quarto',
      placement: 'bottom-start',
    };
    if (contentFn) {
      config.content = contentFn;
    }
    if (onTriggerFn) {
      config.onTrigger = onTriggerFn;
    }
    if (onUntriggerFn) {
      config.onUntrigger = onUntriggerFn;
    }
    window.tippy(el, config); 
  }
  const noterefs = window.document.querySelectorAll('a[role="doc-noteref"]');
  for (var i=0; i<noterefs.length; i++) {
    const ref = noterefs[i];
    tippyHover(ref, function() {
      // use id or data attribute instead here
      let href = ref.getAttribute('data-footnote-href') || ref.getAttribute('href');
      try { href = new URL(href).hash; } catch {}
      const id = href.replace(/^#\/?/, "");
      const note = window.document.getElementById(id);
      if (note) {
        return note.innerHTML;
      } else {
        return "";
      }
    });
  }
  const xrefs = window.document.querySelectorAll('a.quarto-xref');
  const processXRef = (id, note) => {
    // Strip column container classes
    const stripColumnClz = (el) => {
      el.classList.remove("page-full", "page-columns");
      if (el.children) {
        for (const child of el.children) {
          stripColumnClz(child);
        }
      }
    }
    stripColumnClz(note)
    if (id === null || id.startsWith('sec-')) {
      // Special case sections, only their first couple elements
      const container = document.createElement("div");
      if (note.children && note.children.length > 2) {
        container.appendChild(note.children[0].cloneNode(true));
        for (let i = 1; i < note.children.length; i++) {
          const child = note.children[i];
          if (child.tagName === "P" && child.innerText === "") {
            continue;
          } else {
            container.appendChild(child.cloneNode(true));
            break;
          }
        }
        if (window.Quarto?.typesetMath) {
          window.Quarto.typesetMath(container);
        }
        return container.innerHTML
      } else {
        if (window.Quarto?.typesetMath) {
          window.Quarto.typesetMath(note);
        }
        return note.innerHTML;
      }
    } else {
      // Remove any anchor links if they are present
      const anchorLink = note.querySelector('a.anchorjs-link');
      if (anchorLink) {
        anchorLink.remove();
      }
      if (window.Quarto?.typesetMath) {
        window.Quarto.typesetMath(note);
      }
      if (note.classList.contains("callout")) {
        return note.outerHTML;
      } else {
        return note.innerHTML;
      }
    }
  }
  for (var i=0; i<xrefs.length; i++) {
    const xref = xrefs[i];
    tippyHover(xref, undefined, function(instance) {
      instance.disable();
      let url = xref.getAttribute('href');
      let hash = undefined; 
      if (url.startsWith('#')) {
        hash = url;
      } else {
        try { hash = new URL(url).hash; } catch {}
      }
      if (hash) {
        const id = hash.replace(/^#\/?/, "");
        const note = window.document.getElementById(id);
        if (note !== null) {
          try {
            const html = processXRef(id, note.cloneNode(true));
            instance.setContent(html);
          } finally {
            instance.enable();
            instance.show();
          }
        } else {
          // See if we can fetch this
          fetch(url.split('#')[0])
          .then(res => res.text())
          .then(html => {
            const parser = new DOMParser();
            const htmlDoc = parser.parseFromString(html, "text/html");
            const note = htmlDoc.getElementById(id);
            if (note !== null) {
              const html = processXRef(id, note);
              instance.setContent(html);
            } 
          }).finally(() => {
            instance.enable();
            instance.show();
          });
        }
      } else {
        // See if we can fetch a full url (with no hash to target)
        // This is a special case and we should probably do some content thinning / targeting
        fetch(url)
        .then(res => res.text())
        .then(html => {
          const parser = new DOMParser();
          const htmlDoc = parser.parseFromString(html, "text/html");
          const note = htmlDoc.querySelector('main.content');
          if (note !== null) {
            // This should only happen for chapter cross references
            // (since there is no id in the URL)
            // remove the first header
            if (note.children.length > 0 && note.children[0].tagName === "HEADER") {
              note.children[0].remove();
            }
            const html = processXRef(null, note);
            instance.setContent(html);
          } 
        }).finally(() => {
          instance.enable();
          instance.show();
        });
      }
    }, function(instance) {
    });
  }
      let selectedAnnoteEl;
      const selectorForAnnotation = ( cell, annotation) => {
        let cellAttr = 'data-code-cell="' + cell + '"';
        let lineAttr = 'data-code-annotation="' +  annotation + '"';
        const selector = 'span[' + cellAttr + '][' + lineAttr + ']';
        return selector;
      }
      const selectCodeLines = (annoteEl) => {
        const doc = window.document;
        const targetCell = annoteEl.getAttribute("data-target-cell");
        const targetAnnotation = annoteEl.getAttribute("data-target-annotation");
        const annoteSpan = window.document.querySelector(selectorForAnnotation(targetCell, targetAnnotation));
        const lines = annoteSpan.getAttribute("data-code-lines").split(",");
        const lineIds = lines.map((line) => {
          return targetCell + "-" + line;
        })
        let top = null;
        let height = null;
        let parent = null;
        if (lineIds.length > 0) {
            //compute the position of the single el (top and bottom and make a div)
            const el = window.document.getElementById(lineIds[0]);
            top = el.offsetTop;
            height = el.offsetHeight;
            parent = el.parentElement.parentElement;
          if (lineIds.length > 1) {
            const lastEl = window.document.getElementById(lineIds[lineIds.length - 1]);
            const bottom = lastEl.offsetTop + lastEl.offsetHeight;
            height = bottom - top;
          }
          if (top !== null && height !== null && parent !== null) {
            // cook up a div (if necessary) and position it 
            let div = window.document.getElementById("code-annotation-line-highlight");
            if (div === null) {
              div = window.document.createElement("div");
              div.setAttribute("id", "code-annotation-line-highlight");
              div.style.position = 'absolute';
              parent.appendChild(div);
            }
            div.style.top = top - 2 + "px";
            div.style.height = height + 4 + "px";
            div.style.left = 0;
            let gutterDiv = window.document.getElementById("code-annotation-line-highlight-gutter");
            if (gutterDiv === null) {
              gutterDiv = window.document.createElement("div");
              gutterDiv.setAttribute("id", "code-annotation-line-highlight-gutter");
              gutterDiv.style.position = 'absolute';
              const codeCell = window.document.getElementById(targetCell);
              const gutter = codeCell.querySelector('.code-annotation-gutter');
              gutter.appendChild(gutterDiv);
            }
            gutterDiv.style.top = top - 2 + "px";
            gutterDiv.style.height = height + 4 + "px";
          }
          selectedAnnoteEl = annoteEl;
        }
      };
      const unselectCodeLines = () => {
        const elementsIds = ["code-annotation-line-highlight", "code-annotation-line-highlight-gutter"];
        elementsIds.forEach((elId) => {
          const div = window.document.getElementById(elId);
          if (div) {
            div.remove();
          }
        });
        selectedAnnoteEl = undefined;
      };
        // Handle positioning of the toggle
    window.addEventListener(
      "resize",
      throttle(() => {
        elRect = undefined;
        if (selectedAnnoteEl) {
          selectCodeLines(selectedAnnoteEl);
        }
      }, 10)
    );
    function throttle(fn, ms) {
    let throttle = false;
    let timer;
      return (...args) => {
        if(!throttle) { // first call gets through
            fn.apply(this, args);
            throttle = true;
        } else { // all the others get throttled
            if(timer) clearTimeout(timer); // cancel #2
            timer = setTimeout(() => {
              fn.apply(this, args);
              timer = throttle = false;
            }, ms);
        }
      };
    }
      // Attach click handler to the DT
      const annoteDls = window.document.querySelectorAll('dt[data-target-cell]');
      for (const annoteDlNode of annoteDls) {
        annoteDlNode.addEventListener('click', (event) => {
          const clickedEl = event.target;
          if (clickedEl !== selectedAnnoteEl) {
            unselectCodeLines();
            const activeEl = window.document.querySelector('dt[data-target-cell].code-annotation-active');
            if (activeEl) {
              activeEl.classList.remove('code-annotation-active');
            }
            selectCodeLines(clickedEl);
            clickedEl.classList.add('code-annotation-active');
          } else {
            // Unselect the line
            unselectCodeLines();
            clickedEl.classList.remove('code-annotation-active');
          }
        });
      }
  const findCites = (el) => {
    const parentEl = el.parentElement;
    if (parentEl) {
      const cites = parentEl.dataset.cites;
      if (cites) {
        return {
          el,
          cites: cites.split(' ')
        };
      } else {
        return findCites(el.parentElement)
      }
    } else {
      return undefined;
    }
  };
  var bibliorefs = window.document.querySelectorAll('a[role="doc-biblioref"]');
  for (var i=0; i<bibliorefs.length; i++) {
    const ref = bibliorefs[i];
    const citeInfo = findCites(ref);
    if (citeInfo) {
      tippyHover(citeInfo.el, function() {
        var popup = window.document.createElement('div');
        citeInfo.cites.forEach(function(cite) {
          var citeDiv = window.document.createElement('div');
          citeDiv.classList.add('hanging-indent');
          citeDiv.classList.add('csl-entry');
          var biblioDiv = window.document.getElementById('ref-' + cite);
          if (biblioDiv) {
            citeDiv.innerHTML = biblioDiv.innerHTML;
          }
          popup.appendChild(citeDiv);
        });
        return popup.innerHTML;
      });
    }
  }
});
</script>
</div> <!-- /content -->




</body></html>